### ISSUE TITLE
0.4.3 crashes when tapping to download a file

### ISSUE THREAD

**Issue by ripee** [daktak/afh_downloader#15]
This just started yesterday. Attached is my logcat.
[logcat.txt](https://github.com/daktak/afh_downloader/files/1352580/logcat.txt)

This also happens when I made the app a system app.

**Comment by daktak** [comment]
Are you able to share the flid and filename? Also how does it behave if you select web browser in the settings?

**Comment by daktak** [comment]
Issue reproduced, will look into it.

**Comment by daktak** [comment]
I will monitor, but appears AFH is having issues and I cannot download from the website.

**Comment by ripee** [comment]
Thank you for getting back so quickly! This may have something to do with a change AFH made in their system early this week. I have a premium dev subscription but the extra features were missing from my account. AFH Downloader stopped working right when they fixed it, but their site also slowed down considerably at the same time.

**Comment by daktak** [comment]
Ok! In the settings, alter Mirrors Url and remove the www. prefix

**Comment by ripee** [comment]
Great! I can confirm that it works. Just had to close the app and re-open it, clearing its cache or data is unnecessary.

I just compiled version 0.4.4 myself and it works as well!
