### ISSUE TITLE
0.4.4 crashes when trying to download, just as 0.4.3 did

### ISSUE THREAD

**Issue by ripee** [daktak/afh_downloader#18]
AFH made yet another change to the site last night and version 0.4.4 crashes the same way as 0.4.3 crashed.

Side note: removing "www." from the base URL causes the header in the main view to change from "Downloads for : ___________ " to "Loading site please wait..." ...and nothing else appears. Re-adding it doesn't bring back the list of files, nor does re-installing it.

**Comment by daktak** [comment]
Are you able to supply a logcat? Flid 193552 is working for me. Sometimes have to go into settings and back out. Also make sure selector is div[class=file-name] > h3 > a[href^=/?fid=]

**Comment by ripee** [comment]
I tried your Flid and I got the same thing. Here's my logcat using Flid 160136. Believe me, I know that you have to go in and out of settings and close the app from the recent apps view to get it to work. My JSoup select statement is exactly as you wrote, as it's been since 0.4.3.

However, deleting "www." from the base URL sometimes works, but usually it shows nothing.

I also noticed that the added a captcha that appears when the user isn't signed into an account on their site.
[logcat.txt](https://github.com/daktak/afh_downloader/files/1393799/logcat.txt)

**Comment by daktak** [comment]
Damn, the mirrors list spits out this error
This website is using a security service to protect itself from online attacks. You performed an action that triggered the service and blocked your request.

**Comment by daktak** [comment]
0.4.5 has been updated and I've tested currently works.

**Comment by ripee** [comment]
Confirmed that version 0.4.5 works! Thank you!
