### ISSUE TITLE
Removing "www." from the base URL

### ISSUE THREAD

**Issue by ripee** [daktak/afh_downloader#21]
I'd like to suggest removing this because the app refreshes itself much faster if the base URL is just https://androidfilehost.com

**Comment by Ibuprophen** [comment]
I see... The mirror URL default value doesn't have the "www" in it either. 

A very good catch @ripee!!! :-)

**Comment by Ibuprophen** [comment]
I've been working on reviving an old AFH Wrapper App that, so far, has been working very well.

**Comment by ripee** [comment]
I noticed you added a refresh function to your BasketBuild Downloader app. Would something like this be be functional in AFH Downloader, given the way the AFH site is designed? I'll fork your development branch and add that in and test it out for myself.

If so, perhaps an auto-refresh every 5 seconds could help overcome the problem of this app getting stuck on "Loading site please wait..."

**Comment by ripee** [comment]
Actually, the main problem with the app being stuck on "Loading site please wait..." is that it doesn't happen on mobile data, with the wifi only download setting turned off. No matter how strong my wifi signal, the app always gets stuck. On mobile data, no matter how weak the signal, the list of files populates almost instantly. This is with "www." removed from the base URL.
