### ISSUE TITLE
Latest Release Missing... 

### ISSUE THREAD

**Issue by Ibuprophen** [daktak/afh_downloader#23]
I hate to be a bother but, the AFH Downloader v0.4.6 (11) was not pushed to the F-Droid for Download. 

I wasn't sure if you were aware of this @daktak ... :-) 

Thanks a bunch! 

~Ibuprophen

**Comment by daktak** [comment]
https://f-droid.org/wiki/page/org.afhdownloader/lastbuild
https://gitlab.com/fdroid/fdroiddata/commit/1166a7dee4fc50cd3e9c00b342eb4fde731d38c2
I believe that F-droid is processing / updating.

**Comment by Ibuprophen** [comment]
I see that it's on F-Droid now @daktak. 

I wasn't aware of that specific process for F-Droid and I'll definitely keep this in mind. 

Thank you very much for your time, patience, understanding and especially your support for this development!!! 


~Ibuprophen
